import Head from 'next/head';

import React, { useState, useEffect } from 'react';

import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Jumbotron from '../ui-components/Jumbotron';
import ProfileSection from '../components/ProfileSeciton';
import ResumeSection from '../components/ResumeSection';
import GuideSection from '../components/GuideSection';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creasume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/file.ico" />
      </Head>
      <Header />
      <div className={styles.bannerWrapper}>
        <Jumbotron />
      </div>
      <ProfileSection />
      <ResumeSection />
      <GuideSection />
    </div>
  );
}
