import React, { useState } from 'react';
import Head from 'next/head';

import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import loginStyles from '../styles/Login.module.css';
import CustomButton from '../ui-components/CustomButton';

function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  return (
    <div className={styles.container}>
      <Head>
        <title>Creasume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/file.ico" />
      </Head>
      <Header />
      <div className={loginStyles.contentWrapper}>
        <div className={loginStyles.formWrapper}>
          <div className={loginStyles.form}>
            <label for="email">Email</label>
            <br />
            <input
              type="text"
              name="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <br />
            <label for="password">Password</label>
            <br />
            <input
              type="password"
              name="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <br />
            <CustomButton label="Login" variant="contained" color="primary" />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Login;
