import React from 'react';
import Head from 'next/head';

import Header from '../components/Header';
import styles from '../styles/Home.module.css';
import loginStyles from '../styles/Login.module.css';

function Signup() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creasume-Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/file.ico" />
      </Head>
      <Header />
      <div className={loginStyles.contentWrapper}>
        <div className={loginStyles.formWrapper}>
          <div className={loginStyles.buttonWrapper}>
            <div
              className={`${loginStyles.buttonLayout} ${loginStyles.linkedin}`}
            >
              Signup with LinkedIn
            </div>
            <div
              className={`${loginStyles.buttonLayout} ${loginStyles.facebook}`}
            >
              Signup with Facebook
            </div>
            <div className={`${loginStyles.buttonLayout} ${loginStyles.email}`}>
              Signup with Email
            </div>
            <div
              className={`${loginStyles.buttonLayout} ${loginStyles.google}`}
            >
              Signup with Google
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Signup;
